#PATH = '../reddit/output/txt/vr_security_privacy_posts_v2.txt'
#PATH = '../reddit/output/txt/android_security_privacy_posts_v2.txt'
PATH = '../sidequest/output/test_reviews.csv'
DIRECTORY = './results/'
FILENAME = 'keyword_frequencies (sidequest)'